# Generated by Django 5.1.3 on 2025-01-12 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('is_working', models.BooleanField(default=False)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('is_working_requests', models.BooleanField(default=False)),
                ('last_verified_requests', models.DateTimeField(blank=True, null=True)),
                ('is_working_selenium', models.BooleanField(default=False)),
                ('last_verified_selenium', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=10)),
                ('course_number', models.CharField(max_length=10)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(max_length=255)),
                ('instructor', models.CharField(blank=True, max_length=255, null=True)),
                ('term', models.CharField(max_length=50)),
                ('limit', models.IntegerField()),
                ('enrollment', models.IntegerField()),
                ('distrib', models.CharField(blank=True, max_length=50, null=True)),
                ('world_culture', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('period_code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('xlist', models.CharField(blank=True, max_length=255, null=True)),
                ('crn', models.CharField(blank=True, max_length=20, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('class_code', 'course_number', 'section', 'term')},
            },
        ),
        migrations.CreateModel(
            name='EnrollmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.IntegerField()),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_history', to='class_catch_app.class')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('last_notified_enrollment', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscribed_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_catch_app.class')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('email', 'subscribed_class')},
            },
        ),
    ]
