# Generated by Django 5.1.3 on 2025-02-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_catch_app', '0002_alter_subscription_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100, unique=True)),
                ('subject_id', models.CharField(max_length=20)),
                ('course_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('orc_title', models.CharField(blank=True, max_length=255, null=True)),
                ('orc_description', models.TextField(blank=True, null=True)),
                ('distributives', models.JSONField(blank=True, null=True)),
                ('culture_options', models.JSONField(blank=True, null=True)),
                ('schools', models.JSONField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
